version: "3.9"
services:
  mailbox:
    image: leastauthority/magic-wormhole-mailbox:22.11.1
    ports:
      - "4000:4000" # WebSocket
  relay:
    image: leastauthority/magic-wormhole-relay:22.11.1
    ports:
      - "4001:4001" # TCP
      - "4200:4200" # WebSocket
  client:
    build: ./client
    env_file:
      - ./client/.env
    volumes:
      - ./client:/usr/src/app/client
    working_dir: /usr/src/app/client
    command: "npm run serve"
    ports:
      - "8080:8080" # DevServer
      - "35729:35729" # LiveReload
    depends_on:
      - mailbox
      - relay
      - feedback-api
  feedback-api:
    build: ./feedback-api
    command:
      [
        "/app/feedback-api",
        "-to",
        "foo@barbaz.com",
        "-smtp-server",
        "dummy-smtp-server",
        "-smtp-port",
        "1025",
      ]
    ports:
      - "8001:8001"
    depends_on:
      - dummy-smtp-server
    environment:
      - SMTP_USE_TLS=false
      - SMTP_USERNAME=foo@foobar.in
      - SMTP_PASSWORD=barbazquux
  dummy-smtp-server:
    build: ./feedback-api/docker/smtp-server
    ports:
      - "1025:1025"
    environment:
      - PYTHONUNBUFFERED=1
  # Selenium services
  chrome:
    volumes:
      - test-downloads:/home/seluser/downloads
    ports:
      - 5900:5900
      - 7900:7900
    build:
      context: .
      dockerfile: ./client-e2e/images/Dockerfile.chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
      - client
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=1800
      - SE_VNC_NO_PASSWORD=1
    profiles:
      - e2e
  edge:
    volumes:
      - test-downloads:/home/seluser/downloads
    ports:
      - 5901:5900
      - 7901:7900
    build:
      context: .
      dockerfile: ./client-e2e/images/Dockerfile.edge
    shm_size: 2gb
    depends_on:
      - selenium-hub
      - client
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=1800
      - SE_VNC_NO_PASSWORD=1
    profiles:
      - e2e
  firefox:
    volumes:
      - test-downloads:/home/seluser/downloads
    ports:
      - 5902:5900
      - 7902:7900
    build:
      context: .
      dockerfile: ./client-e2e/images/Dockerfile.firefox
    shm_size: 3gb
    depends_on:
      - selenium-hub
      - client
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=1800
      - SE_VNC_NO_PASSWORD=1
    profiles:
      - e2e
  selenium-hub:
    image: selenium/hub:4.9.1-20230508
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test:
        ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - e2e
  client-e2e:
    build: ./client-e2e
    volumes:
      - ./client-e2e:/usr/src/app/client-e2e
      - test-downloads:/home/node/downloads
    working_dir: /usr/src/app/client-e2e
    command: "npm run wdio"
    depends_on:
      client:
        condition: service_started
      selenium-hub:
        condition: service_healthy
    profiles:
      - e2e
volumes:
  test-downloads:
