version: "3.9"
services:
  chrome:
    build:
      dockerfile: ./client-e2e/images/Dockerfile.chrome-arm64
  firefox:
    build:
      dockerfile: ./client-e2e/images/Dockerfile.firefox-arm64
  selenium-hub:
    image: seleniarm/hub:4.11.0-20230801
  client-e2e:
    depends_on:
      chrome:
        condition: service_started
      firefox:
        condition: service_started
