version: "3.9"
services:
  client-e2e:
    depends_on:
      chrome:
        condition: service_started
      edge:
        condition: service_started
      firefox:
        condition: service_started
