version: "3.9"
services:
  mailbox:
    image: leastauthority/magic-wormhole-mailbox:latest
    ports:
      - "4000:4000" # WebSocket
  relay:
    image: leastauthority/magic-wormhole-relay:latest
    ports:
      - "4001:4001" # TCP
      - "4002:4002" # WebSocket
  client:
    build: ./client
    env_file:
      - ./client/.env
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080" # DevServer
      - "35729:35729" # LiveReload
    depends_on:
      - mailbox
      - relay
  # build to run in CI
  client-ci:
    build: ./client
    env_file:
      - ./client/.env
    ports:
      - "8080:8080" # DevServer
      - "35729:35729" # LiveReload
    depends_on:
      - mailbox
      - relay
    profiles:
      - e2e
  # Selenium services
  chrome:
    volumes:
      - test-downloads:/home/seluser/downloads
    ports:
      - "5900:5900"
    build:
      dockerfile: ./client-e2e/images/Dockerfile.chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=1800
    profiles:
      - e2e
  edge:
    volumes:
      - test-downloads:/home/seluser/downloads
    ports:
      - "5901:5900"
    build:
      dockerfile: ./client-e2e/images/Dockerfile.edge
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=1800
    profiles:
      - e2e
  firefox:
    volumes:
      - test-downloads:/home/seluser/downloads
    ports:
      - "5902:5900"
    build:
      dockerfile: ./client-e2e/images/Dockerfile.firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=1800
    profiles:
      - e2e
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test:
        ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - e2e
  client-e2e:
    build: ./client-e2e
    env_file:
      - ./client-e2e/.env
    volumes:
      - ./client-e2e:/usr/src/app/client-e2e
      - test-downloads:/home/node/downloads
    depends_on:
      client-ci:
        condition: service_started
      chrome:
        condition: service_started
      firefox:
        condition: service_started
      edge:
        condition: service_started
      selenium-hub:
        condition: service_healthy
    profiles:
      - e2e
volumes:
  test-downloads:
