---
name: Deploy Key Management

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Deploy Key Rotation
    runs-on: ubuntu-22.04
    steps:
      - name: Current key hash
        run: |
          cat <<EOF | md5
          ${{ secrets.SFTP_IDENTITY }}
          EOF
          cat <<EOF | wc
          ${{ secrets.SFTP_IDENTITY }}
          EOF
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SFTP_IDENTITY }}
      - name: Get authorized keys
        run: |
          cat <<EOF > get_authorized_keys.txt
          open ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOSTNAME }}
          cd .ssh
          get authorized_keys
          bye
          EOF
          sftp -b get_authorized_keyts.txt
          ls -la