---
name: Deploy Key Management

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Deploy Key Rotation
    runs-on: ubuntu-22.04
    steps:
      - name: Current key hash
        run: |
          cat <<EOF | md5sum
          ${{ secrets.SFTP_IDENTITY }}
          EOF
          cat <<EOF | wc
          ${{ secrets.SFTP_IDENTITY }}
          EOF
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SFTP_IDENTITY }}
      - name: Verify host key
        run: |
          mkdir .ssh
          ssh-keyscan ${{ secrets.SFTP_HOSTNAME }} > ~/.ssh/known_hosts 2>/dev/null
      - name: Get authorized keys
        run: |
          cat <<EOF > get_authorized_keys.txt
          cd .ssh
          get authorized_keys
          bye
          EOF
          sftp -b get_authorized_keys.txt ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOSTNAME }}
          ls -la
          cat authorized_keys